### ISSUE TITLE
Bot appears to always to lead first

### ISSUE THREAD

**Issue by Basooka** [gerritsxd/bot-0.1#1]
I've played a couple of games against the bot in single and in multiple formats. In both cases it appears that the bot always starts every game. It does not matter if I win or lose the game. The next game the bot will start. 

I've played the game before and I think I remember being able to start the match too.

**Comment by kms2302** [comment]
This has not been changed by me. In the original platform (as well as ours) bot1 always starts the game as the leaders.

As both the original MLPlayingBot and OkiBot have this advantage (and we are comparing the performance of these bots), this will not have a negative impact on the experiment. I will therefore close this issue.

**Comment by Basooka** [comment]
I agree. I was uncertain about the starting thing. This might have been the case in the old environment uploaded in IS.
It is consistent, but not a true game environment in my opinion.
