### ISSUE TITLE
Server.py "help" error

### ISSUE THREAD

**Issue by Basooka** [gerritsxd/bot-0.1#2]
After the most recent changes we are unable to run the server.py. This is most likely due to a change in line 53.
`    "help='The name of the human that will play 30 games (e.g. Leen)."`
This line appears to be the problem. Deleting it makes me able to run the server with both

> python server.py single -bot Okibot
> python server.py multiple Bas_Admin

**Comment by kms2302** [comment]
This issue was solved in the previous commit (help message moved to docstring).
